version: 2

sphinx:
   configuration: docs/conf.py

build:
  image: latest

python:
   version: 3.7
   setup_py_install: true
   install:
   - requirements: docs/requirements.txt

requirements_file: requirements.txt
